### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by expattaxtools** [iloveicedgreentea/jvc_homeassistant#1]
Hey, thank you for the updated script. The state pulling works perfectly. If you need me to test finished functions on an NZ8, let me know.

**Comment by iloveicedgreentea** [comment]
Sure 👍 

I have tested on my NZ7 but user testing can't hurt. I am slowly working on a bunch of improvements like proper async on the power functions etc. I also want to improve the menu navigation experience as it slow due to the way each command initiates a connection.
