### ISSUE TITLE
Component unstable for JVC DLA-NP5B (Lamp based)

### ISSUE THREAD

**Issue by megapearl** [iloveicedgreentea/jvc_homeassistant#22]
Hi,

Thanks for your great component and all of the work/time you put in it.

The JVC dla-np5 projector is turning on and off sometimes using this component, but a lot of errors appeared in the log, how to troubleshoot?

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:149
Integration: jvc_projectors
First occurred: 09:46:15 (121 occurrences)
Last logged: 09:51:47

Connection timed out. Command b'?\x89\x01PMDC\n' is probably not allowed to run at this time.
Connecting failed, retrying in 2 seconds
retry count for running commands exceeded
```

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/jvc_projectors/remote.py:149
Integration: jvc_projectors
First occurred: 09:46:37 (11 occurrences)
Last logged: 09:51:47

Update for remote.cinema_projector fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 730, in async_device_update
    await task
  File "/home/homeassistant/.homeassistant/custom_components/jvc_projectors/remote.py", line 149, in async_update
    self._laser_mode = await self.jvc_client.async_get_laser_mode()
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 469, in async_get_laser_mode
    return LaserDimModes(state.replace(ACKs.picture_ack.value, b"")).name
TypeError: replace() argument 1 must be str, not bytes
```

```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/jvc_projectors/remote.py:146
Integration: jvc_projectors
First occurred: 09:51:52 (2 occurrences)
Last logged: 09:52:07

Update for remote.cinema_projector fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/home/homeassistant/.homeassistant/custom_components/jvc_projectors/remote.py", line 146, in async_update
    self._lowlatency_enabled = await self.jvc_client.async_get_low_latency_state()
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 421, in async_get_low_latency_state
    state, _ = await self._async_do_reference_op(
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 400, in _async_do_reference_op
    msg, success = await self._async_send_command(
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 150, in _async_send_command
    result, success = await self._async_do_command(
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 225, in _async_do_command
    received_ack = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 447, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/streams.py", line 525, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.10/asyncio/streams.py", line 617, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.10/asyncio/streams.py", line 488, in _wait_for_data
    raise RuntimeError(
RuntimeError: readuntil() called while another coroutine is already waiting for incoming data

```

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:141
Integration: jvc_projectors
First occurred: 09:52:14 (19 occurrences)
Last logged: 09:52:44

Got a blank ack. Restarting connection
Connecting failed, retrying in 2 seconds
Projector did not reply with correct PJ_OK greeting: b''
Connection lost
retry count for running commands exceeded
```

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:146
Integration: jvc_projectors
First occurred: 09:41:58 (249 occurrences)
Last logged: 09:59:05

Connection lost
Connecting failed, retrying in 2 seconds
Got a blank ack. Restarting connection
retry count for running commands exceeded
Connection timed out. Command b'?\x89\x01PMLL\n' is probably not allowed to run at this time.
```

I'm on homeassistant 2022.12.7 and am using v3.0.0 of your component.

How to troubleshoot/debug?

**Comment by iloveicedgreentea** [comment]
Thanks I found a bug I’ll have to fix it. In the meantime downgrade to 2.4.5 and let me know if you still have issues. Jvc connection protocol is really bad and it’s hard to make it work with HA so I need to add some more safeguards

**Comment by iloveicedgreentea** [comment]
I released 3.0.1 can you upgrade, restart, and check logs after 30 seconds again?

**Comment by megapearl** [comment]
Thanks for the quick fix.

v2.4.5 is running stable and without errors, just switched to v3.0.1 so far so good, no errors in logs.
Will test tomorrow the rest of the functionality.

**Comment by iloveicedgreentea** [comment]
Thanks no its not the lamp basically JVC protocol is very sensitive and synchronous while HA needs things to be async. So I have to add a lot of mutexes to ensure only one command is ever running at a time otherwise they step on each other. I will do some more testing tonight

**Comment by iloveicedgreentea** [comment]
I released 3.2.1, please upgrade and try again. I see all attributes working and no errors in logs

**Comment by megapearl** [comment]
Updated to v3.2.1 unfortunately no difference for me, projector turns on, but after that the entities are not updated.

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:144
Integration: jvc_projectors
First occurred: 21:27:20 (270 occurrences)
Last logged: 21:36:20

Connection timed out. Command b'?\x89\x01PMDC\n' is probably not allowed to run at this time.
Connecting failed, retrying in 2 seconds
```

After turning on:

![image](https://user-images.githubusercontent.com/3420660/209403638-eddfc440-d521-491f-85a2-71393973106a.png)

**Comment by iloveicedgreentea** [comment]
Ah I shouldn’t have mad assumptions before sorry. PMDC is the call for laser modes which would fail. Let me add a check which can disable features based on model. Will try to finish that tonight

**Comment by iloveicedgreentea** [comment]
Okay I added a check so it should detect your bulb model and not check for laser status. Let me know if that worked

**Comment by megapearl** [comment]
Typo?

Should I try v3.2.1 or just the 'master' (github) release?

![image](https://user-images.githubusercontent.com/3420660/209431248-7f89a3a8-7771-423c-9038-a939ed6ecc90.png)

**Comment by megapearl** [comment]
Tried v3.3.0 and also not connecting

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:49
Integration: jvc_projectors
First occurred: 11:21:51 (88 occurrences)
Last logged: 11:24:49

Connecting failed, retrying in 2 seconds
```

**Comment by megapearl** [comment]
Tried all versions, and nothing is connecting anymore, I can ping the projector just fine, also resetted it by pulling the plug, it doesn't make any difference.

I changed the last digit of the static IP to +1, and then back to the original ip (resetted network stack of projector), and the component is now connecting again using v3.3.1.

Projector is turned on now, but power state says it is still off.

![image](https://user-images.githubusercontent.com/3420660/209432969-96bd42c8-5cb0-4c77-b63f-dace5ba057f3.png)

**Comment by iloveicedgreentea** [comment]
Okay looks like another command that’s nz only. Sorry I don’t have an nx model to test these so I’ll add it today. For now you can use 2.4.5 if the latest doesn’t work.

**Comment by megapearl** [comment]
Is there any list of commands that are accepted per model?
Is there anything I can do to help?
I can try all the different commands at the cli with the python lib if you want and see which one this model accepts or not.

**Comment by iloveicedgreentea** [comment]
Yeah good idea take a look at the source of this plug-in and you can see what it runs in the update method. Try running each of those to see which ones fail

**Comment by megapearl** [comment]
I will try all the commands, another one which I see often appearing in the logs:

```
This error originated from a custom integration.

Logger: custom_components.jvc_projectors.remote
Source: custom_components/jvc_projectors/remote.py:137
Integration: jvc_projectors
First occurred: December 24, 2022 at 12:04:13 (5900 occurrences)
Last logged: 10:47:45

Received ack did not match expected ack: b'\x06\x89\x01PW\n@\x89\x01PW2\n' != b'\x06\x89\x01PW\n'
retry count for running commands exceeded
Error getting power state: retry count exceeded
Connecting failed, retrying in 2 seconds
Received ack did not match expected ack: b'\x06\x89\x01PW\n@\x89\x01PW0\n' != b'\x06\x89\x01PW\n'
```

**Comment by iloveicedgreentea** [comment]
3.4.0 released which hopefully fixes these issues. I have been running it for a bit and no errors in the logs.

**Comment by megapearl** [comment]
I'm on v.3.4.0 now, I had to pull the plug of the projector to get the component connect to the projector again, maybe because of all previous commands to the projector, running for about 2 hours now, it seems to be stable, will watch it for a week, thanks for all of your support.

**Comment by megapearl** [comment]
Component running stable for a week now,  thanks again!

![image](https://user-images.githubusercontent.com/3420660/212562559-b468e612-5488-4fb3-b0de-a0fd8b728138.png)
