### ISSUE TITLE
After updating from v3.4.1 to v3.4.5 a TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by megapearl** [iloveicedgreentea/jvc_homeassistant#25]
Logger: homeassistant.components.remote
Source: custom_components/jvc_projectors/remote.py:49
Integration: Remote (documentation, issues)
First occurred: 12:43:30 (1 occurrences)
Last logged: 12:43:30

Error while setting up jvc_projectors platform for remote
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/jvc_projectors/remote.py", line 49, in setup_platform
    jvc_client.open_connection()
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 60, in open_connection
    msg, success = self.reconnect()
  File "/srv/homeassistant/lib/python3.10/site-packages/jvc_projector/jvc_projector.py", line 75, in reconnect
    self.client.settimeout(self.connect_timeout)
**TypeError: 'str' object cannot be interpreted as an integer**

**Comment by iloveicedgreentea** [comment]
Can you post your configuration

The scan interval should be an integer not a string. I will add a conversion check

**Comment by megapearl** [comment]
Relevant snippet of configuration.yaml

```
remote:
  - platform: jvc_projectors
    name: Cinema Projector
#    password: ******
    host: cinema-projector.flissinger.local
    timeout: 5
    scan_interval: 15
```

 scan_interval: 15 looks like a integer to me

**Comment by iloveicedgreentea** [comment]
Okay maybe the underlying config is converted as a string inside hass. I will add an int conversion shortly

**Comment by iloveicedgreentea** [comment]
Under HACS, go to the repo, click redownload, and enable beta versions then try 3.4.6. I fixed the issue with types and added a new "timeout" field you should add, 3-5 seconds should work. Let me know how that goes.

**Comment by megapearl** [comment]
A great, it's working again.

![image](https://user-images.githubusercontent.com/3420660/213735915-f85d9a95-a3f8-4f3a-9ace-51290a1b7533.png)

Offtopic: Is it possible to add 'Lamp mode'  for the lamp based projector models?

**Comment by iloveicedgreentea** [comment]
Sure I can look into doing that tonight

**Comment by iloveicedgreentea** [comment]
Actually can you test something for me? Do you have an NX7/8/9? Need to see if content type is supported for you

**Comment by megapearl** [comment]
You need screenshots of the menu?

**Comment by iloveicedgreentea** [comment]
Thanks I am going to release another beta version shortly which enables those things for NX models. Let me know if you get timeouts in your logs which would mean they are not supported.

**Comment by iloveicedgreentea** [comment]
I released 3.4.7 beta can you please update and see what happens? Model should show your correct model and you should see lamp power and hdr populated

**Comment by megapearl** [comment]
Looks good, will test tomorrow when the projector is on and running.

![5F856C12-F2B4-48B0-BEA8-6693D9467B7A](https://user-images.githubusercontent.com/3420660/213769099-977c23f4-44d9-4577-aa84-8d31adf492d1.jpeg)

**Comment by iloveicedgreentea** [comment]
3.5.0 should add in lamp power for you

**Comment by megapearl** [comment]
So far, so good :-)

![image](https://user-images.githubusercontent.com/3420660/213869088-3af99d53-e5bf-4bba-a4a9-a80d68e85514.png)

No errors in logs yet.

**Comment by iloveicedgreentea** [comment]
Thanks for lamp power do you have low med high or just low and high? The API spec only has normal and high, and also no option to get content type

**Comment by megapearl** [comment]
It's just Low and High

![image](https://user-images.githubusercontent.com/3420660/213930373-6e19af50-6601-49cc-8f27-8887a0f909f5.jpeg)

**Comment by iloveicedgreentea** [comment]
okay cool if you encounter any more issues feel free to open an issue 👍
