### ISSUE TITLE
JVC AutoCal doesn't work when integration is enabled

### ISSUE THREAD

**Issue by kernelpanic85** [iloveicedgreentea/jvc_homeassistant#29]
I noticed after adding my JVC NP5 to HA, while everything was working great, I went to run the JVC AutoCal software which connects to the projector over the network, and it was not able to connect.  After commenting out the yaml config and restarting HA, the software was able to connect to the projector again.  Is this a limitation of the projector or do you think something can be done in the integration to fix this?

**Comment by iloveicedgreentea** [comment]
Unfortunately jvc in their infinite wisdom only allows one connection at a time. Nothing I can do about that

**Comment by kernelpanic85** [comment]
Ahh, that's unfortunate.  Thanks for the quick reply!
