### ISSUE TITLE
Power Status issue 

### ISSUE THREAD

**Issue by expattaxtools** [iloveicedgreentea/jvc_homeassistant#6]
The power status stopped working.  The other functions work well.

**Comment by iloveicedgreentea** [comment]
Yeah I had to disable it because it was locking up HA due to simultaneous connections. I am in the middle of a huge rewrite which will use a single long-lived connection and as a side effect will be about 100x faster too, so stay tuned.

**Comment by expattaxtools** [comment]
Exciting. Thank you!

**Comment by iloveicedgreentea** [comment]
https://github.com/iloveicedgreentea/jvc_homeassistant/releases/tag/2.0.0

2.0 is out. I just tested it and it is way faster and all status works as expected. Please let me know if you have any issues with it. Make sure your HA instance updates to the correct library version

**Comment by expattaxtools** [comment]
Not sure what I messed up. I updated both HACS and pip for the new version, but the integration fails to start up.
Here is the error log:

Logger: homeassistant.components.remote
Source: custom_components/jvc_projectors/remote.py:57
Integration: Remote ([documentation](https://www.home-assistant.io/integrations/remote), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+remote%22))
First occurred: 6:30:16 PM (1 occurrences)
Last logged: 6:30:16 PM

Error while setting up jvc_projectors platform for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/jvc_projectors/remote.py", line 57, in async_setup_platform
    JVCRemote(name, host, password, jvc_client),
TypeError: __init__() takes from 3 to 4 positional arguments but 5 were given

**Comment by iloveicedgreentea** [comment]
nope that was not your fault I fixed the bug so please install 2.0.1 and it should work now

**Comment by iloveicedgreentea** [comment]
Released 2.0.2 which adds more reliability to the connection and adds LL status back. I have been running this for a few days without errors so hopefully this fixes all previous issues. Feel free to reopen if you encounter any bugs
